[package]
name = "sentio-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "CLI tool for compiling Sentio processors in Rust"

[[bin]]
name = "sentio"
path = "src/main.rs"

[dependencies]
sentio-sdk = { path = "../sdk" }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }