[package]
name = "eth-basic"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Basic Ethereum processor example using Sentio SDK"

[[bin]]
name = "eth-basic"
path = "src/main.rs"

[dependencies]
sentio-sdk = { path = "../../sdk" }
