[package]
name = "sentio-sdk"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Rust SDK for building Sentio processors"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
async-trait = "0.1"
tonic = "0.12"
prost = "0.13"
prost-types = "0.13"
anyhow = "1.0"
futures = "0.3"
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = "0.4.41"

[build-dependencies]
tonic-build = "0.12"
prost-build = "0.13"
